name: deploy to lambda
on: [push]
env:
  AWS_REGION: ap-southeast-2
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: test
        run: npm i && npm run test
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}

      - name: Zip
        run: cd GetViewCount && npm i && zip -r GetViewCount.zip .
      - name: lambda deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: GetViewCount
          zip_file: GetViewCount/GetViewCount.zip

      - name: Zip
        run: cd UpdateViewCount && npm i && zip -r UpdateViewCount.zip .
      - name: lambda deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: UpdateViewCount
          zip_file: UpdateViewCount/UpdateViewCount.zip

      - name: Zip
        run: cd PostNewPicture && npm i && zip -r PostNewPicture.zip .
      - name: lambda deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: PostNewPicture
          zip_file: PostNewPicture/PostNewPicture.zip

      - name: Zip
        run: cd DeletePicture && npm i && zip -r DeletePicture.zip .
      - name: lambda deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: DeletePicture
          zip_file: DeletePicture/DeletePicture.zip

      - name: Zip
        run: cd GetVisitorGlobeData && npm i && zip -r DeletePicture.zip .
      - name: lambda deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: GetVisitorGlobeData
          zip_file: GetVisitorGlobeData/GetVisitorGlobeData.zip
